events {}

http {
    upstream frontend {
        server project-frontend:80;
    }

    upstream gateway {
        server project-gateway:8000;
    }

    upstream backend {
        server project-backend:8000;
    }

    server {
        listen 80;

        # Health (backend)
        location /health {
            proxy_pass http://backend/health;
        }

        # Stripe webhook (DIRECT, NO REWRITE)
        location /stripe/webhook {
            proxy_pass http://backend/stripe/webhook;
        }

        # API
        location /api/ {
            proxy_pass http://backend/;
        }

        # Frontend
        location / {
            proxy_pass http://frontend/;
        }
    }
}
