server {
    listen 80;
    server_name _;

    # Proxy API requests to gateway container
    location /api/ {
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

        rewrite ^/api(/.*)$ $1 break;
        proxy_pass http://project-gateway:9002/;
    }

    # WebSocket path
    location /ws/ {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        rewrite ^/ws(/.*)$ $1 break;
        proxy_pass http://project-gateway:9002/;
    }

    # static frontend fallback
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
