services:
  nginx:
    image: nginx:alpine
    container_name: project-nginx
    depends_on:
      - frontend
      - gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
